# Generated by Django 2.2.7 on 2023-05-15 01:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 1, 3, 31, 71508, tzinfo=utc)),
        ),
    ]
