# Generated by Django 2.2.7 on 2023-05-15 03:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230515_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 3, 38, 39, 320640, tzinfo=utc)),
        ),
    ]
