# Generated by Django 2.2.7 on 2023-05-17 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230517_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 8, 38, 46, 35926, tzinfo=utc)),
        ),
    ]
