# Generated by Django 4.2.1 on 2023-05-23 07:54

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230517_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 7, 54, 27, 536899, tzinfo=datetime.timezone.utc)),
        ),
    ]
