# Generated by Django 4.2.1 on 2023-05-25 06:27

import datetime
from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_mission_body_alter_mission_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='body',
            field=django_summernote.fields.SummernoteTextField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 6, 27, 19, 292244, tzinfo=datetime.timezone.utc)),
        ),
    ]
